add code

diff --git a/.github/workflows/go-critic-analysis.yml b/.github/workflows/go-critic-analysis.yml
--- a/.github/workflows/go-critic-analysis.yml
+++ b/.github/workflows/go-critic-analysis.yml
@@ -51,6 +51,7 @@ jobs:
           # 循环处理 repo.txt 中的每个仓库
           while IFS= read -r repo; do
             echo "Processing $repo"
+            echo "Processing $repo" > ../../gocritic-errors-$repo_name.txt
             repo_name=$(basename -s .git "$repo")
 
             # 克隆仓库
@@ -58,7 +59,7 @@ jobs:
             cd "$repo_name"
 
             # 运行 go-critic 并捕获错误输出
-            gocritic check  -disable sloppyTypeAssert,singleCaseSwitch,captLocal,ifElseChain,caseOrder,unslice,commentFormatting,assignOp,exitAfterDefer,elseif,wrapperFunc,unlambda,underef,badCall,dupSubExpr,sloppyLen,offBy1,defaultCaseOrder > ../../gocritic-report-$repo_name.txt 2> ../../gocritic-errors-$repo_name.txt || true
+            gocritic check  -disable sloppyTypeAssert,singleCaseSwitch,captLocal,ifElseChain,caseOrder,unslice,commentFormatting,assignOp,exitAfterDefer,elseif,wrapperFunc,unlambda,underef,badCall,dupSubExpr,sloppyLen,offBy1,defaultCaseOrder,deprecatedComment > ../../gocritic-report-$repo_name.txt 2 > ../../gocritic-errors-$repo_name.txt || true
 
             #go vet  || true
             #gocritic check  > ../../gocritic-report-$repo_name.txt 2> ../../gocritic-errors-$repo_name.txt || true
